apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-353214
  # used to resolve build not found error
  tagPolicy:
    sha256: {}
  artifacts:
    - image: us.gcr.io/ticketing-dev-353214/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-353214/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-353214/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-353214/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-353214/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-353214/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .



# apiVersion: skaffold/v2beta4
# kind: Config
# build:
#   tagPolicy:
#     sha256: {}
#   artifacts:
#     - image: us.gcr.io/ticketing-dev-353214/auth
#       context: auth
#       sync:
#         infer:
#           - 'src/**/*.ts'
#         # manual:
#         #   - src: "src/**/*.ts"
#         #     dest: .
#     - image: us.gcr.io/ticketing-dev-353214/client
#       context: client
#       sync:
#         infer:
#           - 'src/**/*.js'
#         # manual:
#         #   - src: "src/**/*.ts"
#         #     dest: .
 
# # Deployment
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
 
# # Deployment setting
# profiles:
#   - name: cloudbuild
#     build:
#       googleCloudBuild: { projectId: ticketing-dev-353214}
#       artifacts:
#         - image: us.gcr.io/ticketing-dev-353214/auth
#           context: auth
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - 'src/**/*.ts'
#             # manual:
#             #   - src: "src/**/*.ts"
#             #     dest: .
#         - image: us.gcr.io/ticketing-dev-353214/client           
#           context: client
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - '**/*.js'

    